baseurl: /
languageCode: de-de
title: Marlene Erschbamer
copyright: © Marlene Erschbamer
disableKinds:
  - taxonomy
  - taxonomyTerm
theme: hugo-theme-doors
disableRSS: yes
disableSitemap: yes
disable404: yes
params:
  contact:
    description:
    email: 'marlene@erschbamer.net'
    facebook: 'https://www.facebook.com/profile.php?id=61577383696807'
    github: ''
    instagram: 'https://www.instagram.com/erinnermich_blog/'
    linkedin: 'https://www.linkedin.com/in/marlene-erschbamer-786aa3145/'
    twitter: ''
  description: ''
  googleTagManager: GTM-xxxxxxxx
  ogimage: images/work1.jpg
  projects:
    list:
      - description: Marlene Erschbamer alias Fiona Novale
        h: '240'
        image: images/nepal.jpg
        title: Tätigkeitsfelder
        url: '#'
        w: '780'
  subprojects:
    list:
      - description: 'Wo wissenschaftliche Tiefe auf kreative Inspiration trifft – maßgeschneiderte Texte, Workshops und Korrektorat für Ihre Projekte.'
        h: '522'
        image: images/MusE.jpg
        title: MusE - Marlene Erschbamer
        url: 'https://muse.erschbamer.net/'
        w: '780'
      - description: 'Gedichte - Kurzeschichten - Romane. Aktuelles Werk: Der Gesellschaftsroman Zeitwunden (2025) über generationsübergreifende Traumata und Gewalt an Frauen.'
        h: '532'
        image: images/fiona.jpg
        title: Fiona Novale - Autorin
        url: 'https://fiona-novale.erinnermich.eu/'
        w: '780'
      - description: 'Ein Blog über Herstory, um Frauen und ihren Leistungen sichtbar zu machen.'
        h: '522'
        image: images/blog.png
        title: Erinnermich - Frauen.schreiben.Geschichte.
        url: 'https://erinnermich.eu/'
        w: '780'
      - description: 'Marlene Erschbamer is a scholar in Tibetan Studies whose research centers on the intersections of lineage (Barawa Kagyu), gender, and regional history (Sikkim) in the Himalayas.'
        h: '518'
        image: images/studies.jpg
        title: Himalayan, Tibetan, and Buddhist Studies
        url: 'https://scholar.erschbamer.net/'
        w: '780'

