baseurl: /
languageCode: de-de
title: Marlene Erschbamer
copyright: © Marlene Erschbamer
disableKinds:
  - taxonomy
  - taxonomyTerm
theme: hugo-theme-doors
disableRSS: yes
disableSitemap: yes
disable404: yes
params:
  contact:
    description:
    email: 'marlene@erschbamer.net'
    facebook: ''
    github: ''
    instagram: 'https://www.instagram.com/erinnermich_blog/'
    linkedin: 'https://www.linkedin.com/in/marlene-erschbamer-786aa3145/'
    twitter: ''
  description: 'Marlene Erschbamer ist Tibetologin, Philosophin und Autorin. Unter dem Pseudonym Fiona Novale veröffentlichte sie den Roman Zeitwunden. Ihre Expertise fließt auch in pädagogische Projekte ein, darunter maßgeschneiderte Workshops für Schulklassen. Auf ihrem Blog Erinnermich – Frauen.schreiben.Geschichte teilt sie inspirierende Beiträge. Eine Welt, in der Wissen und Kreativität aufeinandertreffen.'
  googleTagManager: GTM-xxxxxxxx
  ogimage: images/work1.jpg
  projects:
    list:
      - description: Marlene Erschbamer alias Fiona Novale
        h: '240'
        image: images/nepal.jpg
        title: Tätigkeitsfelder
        url: '#'
        w: '780'
  subprojects:
    list:
      - description: Kreatives Schreiben, Workshops, Korrekturlesen
        h: '522'
        image: images/MusE.png
        title: Creative Writing
        url: 'https://muse.erschbamer.net/'
        w: '780'
      - description: Himalayan, Tibetan, and Buddhist Studies
        h: '518'
        image: images/Sikkim.jpg
        title: Independent Scholar
        url: 'https://scholar.erschbamer.net/'
        w: '780'
      - description: Frauen.schreiben.Geschichte
        h: '522'
        image: images/blog.png
        title: Erinnermich - Blog
        url: 'https://erinnermich.eu/'
        w: '780'
      - description: Autorin - Roman Zeitwunden
        h: '532'
        image: images/buch_logo.jpg
        title: Fiona Novale
        url: 'https://fiona-novale.erinnermich.eu/'
        w: '780'
